name: Auto Update README.md

on:
    watch:
        types: [started]

jobs:
    update:
        runs-on: ubuntu-latest
        env:
            GITHUB_ACTOR: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            UNSPLASH_TOKEN: ${{ secrets.UNSPLASH_TOKEN }}
        steps:
            - uses: actions/checkout@v2
            - name: Update README.md
              run: |
                  RESPONSE=`curl -s -X GET https://api.unsplash.com/photos/random/?query=nature -H "Authorization: Client-ID $UNSPLASH_TOKEN"`
                  URL=`echo "$RESPONSE" | jq -r '.urls.raw'`
                  ACTOR=$GITHUB_ACTOR
                  TODAY=`date +'%d/%m/%Y'`
                  TAG='<img src=\"'$URL'/&fm=jpg&crop=faces&fit=crop&h=540&w=1920\"/>⭐️ [Star](https://github.com/baradghimire/baradghimire) this repo to update the header image. Last starred by ['$ACTOR'](https://github.com/'$ACTOR') on ['$TODAY'](https://github.com/baradghimire/baradghimire/actions)'
                  FINAL=$(sed 's|&|\\&|g' <<< $TAG)
                  sed -i "1s~.*~$FINAL~" README.md
            - name: Git add, commit, push
              run: |
                  git config --global user.name "baradghimire"
                  git config --global user.email "baradghimire@gmail.com"
                  git add README.md
                  git commit -m "Thank you for the star, $ACTOR"
                  git push
